<img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTaJWG7PzF3toxaRMB1-JicpqMgJuEXATd0fg&" style="width: 150px;margin-top:30px;" align ="center">


<div style= "font-size: 40px;font-weight:bold; font-family: 'Avenir Next LT Pro', sans-serif;"><center>To Grant or Not to Grant</center></div> <br>

<div style= "font-size: 27px;font-weight:bold;line-height: 1.1; margin-top:40px; font-family: 'Avenir Next LT Pro', sans-serif;"><center>Machine Learning Project 2024/2025</center></div> <br>

   <div style= "font-size: 20px;font-weight:bold; font-family: 'Avenir Next LT Pro', sans-serif;"><center> Group 42:</center></div>
   <div><center> Eden da Silva | 20240740 </center></div>
   <div><center> José Cavaco | 20240513 </center></div>
   <div><center> Luana Rocha | 20240111 </center></div>
   <div><center> Maria Radix | 20240687 </center></div>
   <div><center> Tiago Castilho | 20240489 </center></div>

# Notebook 6: Modeling
# Index

* [6.0. Imports](#imp)

* [6.1. SMOTE](#smote)

* [6.2. Models](#models)
  * [6.2.1. Random Forest](#rf)
  * [6.2.2. Neural Network](#nn)
  * [6.2.3. K Nearest Neighbors](#knn)
  * [6.2.4. Decision Tree](#tree)
  * [6.2.5. Logistic Regression](#logreg)
  * [6.2.6. Gradient Boosting](#gradient)
  * [6.2.7. Ensemble](#ens)
  * [6.2.8 XGBoost](#xgb)
 * [6.3 Kaggle Submission](#kaggle)

<hr>
<div class="alert alert-block alert-info" style="font-size:12px" id="imp">
    
# **6.0. Imports**
 
</a>

In [1]:
import pandas as pd
import numpy as np

from sklearn.metrics import classification_report, accuracy_score, confusion_matrix, f1_score

from sklearn.ensemble import RandomForestClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import MultinomialNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import StackingClassifier
from xgboost import XGBClassifier

from imblearn.over_sampling import SMOTE

import warnings
warnings.filterwarnings('ignore')

In [3]:
#importing

df_train_log_minmax_fs = pd.read_csv('df_train_log_minmax_fs.csv', low_memory=False, index_col = 0)
df_val_log_minmax_fs = pd.read_csv('df_val_log_minmax_fs.csv', low_memory=False, index_col = 0)

test_data = pd.read_csv('df_test_log_minmax_fs.csv', low_memory=False, index_col = 0)

In [4]:
X_train = df_train_log_minmax_fs.drop('Claim Injury Type', axis = 1)
X_val = df_val_log_minmax_fs.drop('Claim Injury Type', axis = 1)

y_train = df_train_log_minmax_fs['Claim Injury Type']
y_val = df_val_log_minmax_fs['Claim Injury Type']

<hr>
<div class="alert alert-block alert-info" style="font-size:12px" id="smote">
    
# **6.1. SMOTE**
 
</a>

We will use Synthetic Minority Oversampling Technique (SMOTE) to solve the class imbalance that is present in our target feature, Claim Injury Type. From previous feature exploration, we know the categories that represent extreme case injuries (categories 7 and 8) are very rare. SMOTE works by analyzing the categories with few values and generating similar points. The addition of these 'synthetic' points helps to balance the dataset, making it easier for models to predict the more rare categories.

Source: https://www.analyticsvidhya.com/blog/2020/10/overcoming-class-imbalance-using-smote-techniques/

In [9]:
# Initialize SMOTE
smote = SMOTE(random_state=1)

# Resample the training data
X_train_resampled, y_train_resampled = smote.fit_resample(X_train, y_train)

<hr>
<div class="alert alert-block alert-info" style="font-size:12px" id="models">
    
# **6.2. Models**
 
</a>

<hr>
<div class="alert alert-block alert-info" style="font-size:12px" id="rf">
    
# 6.2.1. Random Forest
 
</a>

In [9]:
# # Initialize Random Forest Classifier
# rf = RandomForestClassifier(n_estimators=100, random_state=42)
# rf.fit(X_train_resampled, y_train_resampled)

# # Predict and evaluate

# y_train_pred_rf = rf.predict(X_train)
# y_val_pred_rf = rf.predict(X_val)

# print("Accuracy Train Score:", accuracy_score(y_train, y_train_pred_rf))
# print("Accuracy Val Score:", accuracy_score(y_val, y_val_pred_rf))
# print("\nConfusion Matrix:")
# print(confusion_matrix(y_val, y_val_pred_rf))
# print("\nClassification Report:")
# print(classification_report(y_val, y_val_pred_rf))

Accuracy Train Score: 0.9999781380943705
Accuracy Val Score: 0.7810812223422419

Confusion Matrix:
[[ 1456   916    80    39     5     0     0     0]
 [  782 55706  1121   550    44     0     0     5]
 [   48  7011  1600  4421   686     8     0     6]
 [   35  1349   820 24757  2622   101     0    17]
 [    0    22    82  3453  6073    26     0     0]
 [    0     2    13   665   125    36     0     1]
 [    0     0     1    13     2     2     0     1]
 [    2    21     7    27     0     0     0    37]]

Classification Report:
              precision    recall  f1-score   support

           1       0.63      0.58      0.60      2496
           2       0.86      0.96      0.90     58208
           3       0.43      0.12      0.18     13780
           4       0.73      0.83      0.78     29701
           5       0.64      0.63      0.63      9656
           6       0.21      0.04      0.07       842
           7       0.00      0.00      0.00        19
           8       0.55      0.39  

<hr>
<div class="alert alert-block alert-info" style="font-size:12px" id="nn">
    
# 6.2.2. Neural Network
 
</a>

In [10]:
# # Initialize and train MLP Classifier
# mlp = MLPClassifier(random_state=42)
# mlp.fit(X_train_resampled, y_train_resampled)

# # Predict and evaluate
# y_train_pred_mlp = mlp.predict(X_train)
# y_val_pred_mlp = mlp.predict(X_val)

# print("Accuracy Train Score:", accuracy_score(y_train, y_train_pred_mlp))
# print("Accuracy Val Score:", accuracy_score(y_val, y_val_pred_mlp))
# print("\nConfusion Matrix:")
# print(confusion_matrix(y_val, y_val_pred_mlp))
# print("\nClassification Report:")
# print(classification_report(y_val, y_val_pred_mlp))

Accuracy Train Score: 0.7477038926337524
Accuracy Val Score: 0.7437976932994181

Confusion Matrix:
[[ 1649   699    83    49     8     1     1     6]
 [ 2110 53327  1589  1006    96     8     2    70]
 [  206  6703  1712  4068   864   183     4    40]
 [  125  1330   943 21788  3708  1704    23    80]
 [    0    46   110  2516  6607   364     8     5]
 [    0     2    15   405   163   253     2     2]
 [    0     0     2     6     4     6     0     1]
 [    4    14     6    19     1     1     0    49]]

Classification Report:
              precision    recall  f1-score   support

           1       0.40      0.66      0.50      2496
           2       0.86      0.92      0.89     58208
           3       0.38      0.12      0.19     13780
           4       0.73      0.73      0.73     29701
           5       0.58      0.68      0.63      9656
           6       0.10      0.30      0.15       842
           7       0.00      0.00      0.00        19
           8       0.19      0.52  

<hr>
<div class="alert alert-block alert-info" style="font-size:12px" id="knn">
    
# 6.2.3. KNN
 
</a>

In [11]:
# knn = KNeighborsClassifier(n_neighbors=5)
# knn.fit(X_train_resampled, y_train_resampled)

# # Predict and evaluate
# y_train_pred_knn = knn.predict(X_train)
# y_val_pred_knn = knn.predict(X_val)

# print("Accuracy Train Score:", accuracy_score(y_train, y_train_pred_knn))
# print("Accuracy Val Score:", accuracy_score(y_val, y_val_pred_knn))
# print("\nConfusion Matrix:")
# print(confusion_matrix(y_val, y_val_pred_knn))
# print("\nClassification Report:")
# print(classification_report(y_val, y_val_pred_knn))

Accuracy Train Score: 0.8086888929373899
Accuracy Val Score: 0.5621711557894004

Confusion Matrix:
[[ 1634   518   242    64    31     4     1     2]
 [ 4602 37814 13963  1378   352    42     1    56]
 [  613  4612  4208  2751  1300   253     7    36]
 [  486  1850  4876 14893  5526  1920    66    84]
 [   41   115   930  2223  5750   567    13    17]
 [    3     2    68   331   232   199     4     3]
 [    0     1     0     5     3     8     1     1]
 [    3    16     9    18     8     3     1    36]]

Classification Report:
              precision    recall  f1-score   support

           1       0.22      0.65      0.33      2496
           2       0.84      0.65      0.73     58208
           3       0.17      0.31      0.22     13780
           4       0.69      0.50      0.58     29701
           5       0.44      0.60      0.50      9656
           6       0.07      0.24      0.10       842
           7       0.01      0.05      0.02        19
           8       0.15      0.38  

<hr>
<div class="alert alert-block alert-info" style="font-size:12px" id="tree">
    
# 6.2.4. Decision Tree
 
</a>

In [13]:
# # Initialize the Decision Tree model
# dt_model = DecisionTreeClassifier(random_state=42)

# # Train the model
# dt_model.fit(X_train_resampled, y_train_resampled)

# # Predict and evaluate
# y_train_pred_dt = dt_model.predict(X_train)
# y_val_pred_dt = dt_model.predict(X_val)

# print("Accuracy Train Score:", accuracy_score(y_train, y_train_pred_dt))
# print("Accuracy Val Score:", accuracy_score(y_val, y_val_pred_dt))
# print("\nConfusion Matrix:")
# print(confusion_matrix(y_val, y_val_pred_dt))
# print("\nClassification Report:")
# print(classification_report(y_val, y_val_pred_dt))

Accuracy Train Score: 0.9999781380943705
Accuracy Val Score: 0.6607982856545525

Confusion Matrix:
[[ 1291   922   181    97     4     0     0     1]
 [ 1750 47307  7687  1354    76     6     0    28]
 [  228  5774  3331  3434   890   107     6    10]
 [  132  1249  4527 18536  4338   852    22    45]
 [    4    74   974  3126  5254   219     2     3]
 [    1     6    63   472   193   106     0     1]
 [    0     1     0     9     4     4     0     1]
 [    5    12    18    23     1     3     0    32]]

Classification Report:
              precision    recall  f1-score   support

           1       0.38      0.52      0.44      2496
           2       0.85      0.81      0.83     58208
           3       0.20      0.24      0.22     13780
           4       0.69      0.62      0.65     29701
           5       0.49      0.54      0.51      9656
           6       0.08      0.13      0.10       842
           7       0.00      0.00      0.00        19
           8       0.26      0.34  

<hr>
<div class="alert alert-block alert-info" style="font-size:12px" id="logred">
    
# 6.2.5. Logistic Regression
 
</a>

In [14]:
# log_reg = LogisticRegression()

# log_reg.fit(X_train_resampled, y_train_resampled)

# # Predict and evaluate
# y_train_pred_lr = log_reg.predict(X_train)
# y_val_pred_lr = log_reg.predict(X_val)

# print("Accuracy Train Score:", accuracy_score(y_train, y_train_pred_lr))
# print("Accuracy Val Score:", accuracy_score(y_val, y_val_pred_lr))
# print("\nConfusion Matrix:")
# print(confusion_matrix(y_val, y_val_pred_lr))
# print("\nClassification Report:")
# print(classification_report(y_val, y_val_pred_lr))

Accuracy Train Score: 0.5772514726422542
Accuracy Val Score: 0.5770410118819471

Confusion Matrix:
[[ 1674   469   216    58    17    17     3    42]
 [ 6182 42491  6392  2131   510    58    23   421]
 [  794  4639  2774  2814  1462   900   188   209]
 [  465   336  1293 12990  6090  6142  1918   467]
 [    2     0    56  1690  5712  1675   450    71]
 [    1     0     5    63    99   512   147    15]
 [    0     0     0     0     2     6     9     2]
 [    1     0     4     1     2     1     5    80]]

Classification Report:
              precision    recall  f1-score   support

           1       0.18      0.67      0.29      2496
           2       0.89      0.73      0.80     58208
           3       0.26      0.20      0.23     13780
           4       0.66      0.44      0.53     29701
           5       0.41      0.59      0.49      9656
           6       0.05      0.61      0.10       842
           7       0.00      0.47      0.01        19
           8       0.06      0.85  

<hr>
<div class="alert alert-block alert-info" style="font-size:12px" id="gb">
    
# 6.2.6. Gradient Boosting
 
</a>

In [17]:
# #Gradient Boosting Classifier
# GB = GradientBoostingClassifier(
#     n_estimators=200,            
#     learning_rate=0.1,          
#     max_depth=5,                 
#     min_samples_split=5,         
#     max_features='sqrt',         
#     random_state=42)

# # Training the model
# GB.fit(X_train_resampled, y_train_resampled)

# # Predict and evaluate
# y_train_pred_gb = GB.predict(X_train)
# y_val_pred_gb = GB.predict(X_val)

# print("Accuracy Train Score:", accuracy_score(y_train, y_train_pred_gb))
# print("Accuracy Val Score:", accuracy_score(y_val, y_val_pred_gb))
# print("\nConfusion Matrix:")
# print(confusion_matrix(y_val, y_val_pred_gb))
# print("\nClassification Report:")
# print(classification_report(y_val, y_val_pred_gb))

Accuracy Train Score: 0.7735276613833728
Accuracy Val Score: 0.7707150074915502

Confusion Matrix:
[[ 1549   815    58    58     6     1     1     8]
 [ 1274 55209  1074   537    58     1     0    55]
 [   69  7050  1523  4280   747    79     2    30]
 [   70  1355   723 23413  3178   877     8    77]
 [    0    42    61  2851  6536   164     1     1]
 [    0     2    10   498   142   185     3     2]
 [    0     0     1    10     4     3     0     1]
 [    2    16     2    13     0     0     1    60]]

Classification Report:
              precision    recall  f1-score   support

           1       0.52      0.62      0.57      2496
           2       0.86      0.95      0.90     58208
           3       0.44      0.11      0.18     13780
           4       0.74      0.79      0.76     29701
           5       0.61      0.68      0.64      9656
           6       0.14      0.22      0.17       842
           7       0.00      0.00      0.00        19
           8       0.26      0.64  

<hr>
<div class="alert alert-block alert-info" style="font-size:12px" id="ens">
    
# 6.2.7. Ensemble
 
</a>

In [22]:
# estimators = [
#     ('rf', RandomForestClassifier(n_estimators=100, criterion="gini", max_features='sqrt', random_state=5, max_depth=8)),
#     ('lr', LogisticRegression(max_iter=1000, random_state=5))
# ]

# sc = StackingClassifier(estimators=estimators, final_estimator=GaussianNB())

# sc.fit(X_train_resampled, y_train_resampled)

# # Predict and evaluate
# y_train_pred_sc = sc.predict(X_train)
# y_val_pred_sc = sc.predict(X_val)

# print("Accuracy Train Score:", accuracy_score(y_train, y_train_pred_sc))
# print("Accuracy Val Score:", accuracy_score(y_val, y_val_pred_sc))
# print("\nConfusion Matrix:")
# print(confusion_matrix(y_val, y_val_pred_sc))
# print("\nClassification Report:")
# print(classification_report(y_val, y_val_pred_sc))

Accuracy Train Score: 0.6147737900042509
Accuracy Val Score: 0.616188717376912

Confusion Matrix:
[[ 1684   622   106    32    11     3     2    36]
 [ 4799 49325  2756   912    90    25     1   300]
 [  508  6509  1280  2753  1912   630    49   139]
 [  307   732  1225 11088  8556  6700   811   282]
 [    0     0    16   869  6710  1926   112    23]
 [    0     0     6    16   159   562    94     5]
 [    0     0     0     0     2     6    10     1]
 [    3     1     3     7     0     1     2    77]]

Classification Report:
              precision    recall  f1-score   support

           1       0.23      0.67      0.34      2496
           2       0.86      0.85      0.85     58208
           3       0.24      0.09      0.13     13780
           4       0.71      0.37      0.49     29701
           5       0.38      0.69      0.50      9656
           6       0.06      0.67      0.11       842
           7       0.01      0.53      0.02        19
           8       0.09      0.82   

<hr>
<div class="alert alert-block alert-info" style="font-size:12px" id="xgb">
    
# 6.2.8. XGBoost
 
</a>

In [11]:
## XGB expects y to start from 0 so we changed y_train and y_val

y_train_xgb_res = y_train_resampled - 1
y_train_xgb = y_train - 1
y_val_xgb = y_val - 1

# Initialize and train XGBoost
xgb = XGBClassifier()

xgb.fit(X_train_resampled, y_train_xgb_res)

# Predict and evaluate
y_train_pred_xgb = xgb.predict(X_train)
y_val_pred_xgb = xgb.predict(X_val)

print("Accuracy Train Score:", accuracy_score(y_train_xgb, y_train_pred_xgb))
print("Accuracy Val Score:", accuracy_score(y_val_xgb, y_val_pred_xgb))
print("\nConfusion Matrix:")
print(confusion_matrix(y_val_xgb, y_val_pred_xgb))
print("\nClassification Report:")
print(classification_report(y_val_xgb, y_val_pred_xgb))

Accuracy Train Score: 0.78846250171501
Accuracy Val Score: 0.7812293111258232

Confusion Matrix:
[[ 1585   791    62    46     8     0     0     4]
 [ 1101 55928   724   383    50     2     0    20]
 [   52  7229  1557  4148   703    65     2    24]
 [   72  1311   881 23612  2897   856    11    61]
 [    2    22    99  2595  6752   183     2     1]
 [    0     1    11   499   136   190     3     2]
 [    0     0     2     8     3     5     0     1]
 [    1    14     2    19     0     0     0    58]]

Classification Report:
              precision    recall  f1-score   support

           0       0.56      0.64      0.60      2496
           1       0.86      0.96      0.91     58208
           2       0.47      0.11      0.18     13780
           3       0.75      0.79      0.77     29701
           4       0.64      0.70      0.67      9656
           5       0.15      0.23      0.18       842
           6       0.00      0.00      0.00        19
           7       0.34      0.62    

<hr>
<div class="alert alert-block alert-info" style="font-size:12px" id="kaggle">
    
# 6.3. Kaggle Submission
 
</a>

In [8]:
test_data['Claim Injury Type'] = xgb.predict(test_data)

In [10]:
## only for xgb
test_data['Claim Injury Type'] = test_data['Claim Injury Type']+1

In [11]:
kaggle_submission = test_data[['Claim Injury Type']].copy()

In [12]:
print(kaggle_submission)

                  Claim Injury Type
Claim Identifier                   
6165911                           2
6166141                           2
6165907                           2
6166047                           2
6166102                           2
...                             ...
6553137                           1
6553119                           1
6553542                           1
6553455                           1
6553594                           1

[387975 rows x 1 columns]


In [13]:
#creating a dictionary so that we can access Claim Injury Type descriptions when we make our predictions with the model
claim_injury_type_dict = {1: '1. CANCELLED', 2: '2. NON-COMP', 3: '3. MED ONLY', 4: '4. TEMPORARY', 5: '5. PPD SCH LOSS',
                           6: '6. PPD NSL', 7: '7. PTD', 8: '8. DEATH'}

In [14]:
kaggle_submission['Claim Injury Type'] = kaggle_submission['Claim Injury Type'].map(claim_injury_type_dict)

In [15]:
#export test data predictions
kaggle_submission.to_csv('ClaimInjuryType_predictions3.csv')